# Generated by Django 5.2.5 on 2025-09-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('published_date', models.DateField()),
                ('publication_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'permissions': [('can_create', 'Can create a book'), ('can_edit', 'Can edit a book'), ('can_delete', 'Can delete a book'), ('can_view', 'Can view a book')],
            },
        ),
    ]
